In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('train.csv', header=0)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 90.5+ KB

In [6]:
unnecessary_columns=['Name', 'Ticket', 'Cabin']

In [7]:
df=df.drop(unnecessary_columns, axis=1)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(2)
memory usage: 69.6+ KB

In [9]:
dummies=[]
cols=['Pclass', 'Sex', 'Embarked']
for col in cols:
    dummies.append(pd.get_dummies(df[col]))

In [10]:
titanic_dummies=pd.concat(dummies, axis=1)

In [11]:
df=pd.concat((df, titanic_dummies), axis=1)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 17 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       889 non-null object
1              891 non-null float64
2              891 non-null float64
3              891 non-null float64
female         891 non-null float64
male           891 non-null float64
C              891 non-null float64
Q              891 non-null float64
S              891 non-null float64
dtypes: float64(10), int64(5), object(2)
memory usage: 125.3+ KB

In [13]:
df=df.drop(['Pclass', 'Sex', 'Embarked'], axis=1)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 14 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
1              891 non-null float64
2              891 non-null float64
3              891 non-null float64
female         891 non-null float64
male           891 non-null float64
C              891 non-null float64
Q              891 non-null float64
S              891 non-null float64
dtypes: float64(10), int64(4)
memory usage: 104.4 KB

In [15]:
df.head()

,PassengerId,Survived,Age,SibSp,Parch,Fare,1,2,3,female,male,C,Q,S
0,1,0,22,1,0,7.2500,0,0,1,0,1,0,0,1
1,2,1,38,1,0,71.2833,1,0,0,1,0,1,0,0
2,3,1,26,0,0,7.9250,0,0,1,1,0,0,0,1
3,4,1,35,1,0,53.1000,1,0,0,1,0,0,0,1
4,5,0,35,0,0,8.0500,0,0,1,0,1,0,0,1

In [16]:
df['Age']=df['Age'].interpolate()

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 14 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
1              891 non-null float64
2              891 non-null float64
3              891 non-null float64
female         891 non-null float64
male           891 non-null float64
C              891 non-null float64
Q              891 non-null float64
S              891 non-null float64
dtypes: float64(10), int64(4)
memory usage: 104.4 KB

In [18]:
X=df.values
y=df['Survived'].values

In [19]:
import numpy as np

In [20]:
#Delete Survived Column
X=np.delete(X, 1, axis=1)

In [21]:
from sklearn import cross_validation
#Split Train and Test Set

X_train, X_test, y_train, y_test=cross_validation.train_test_split(X, y, test_size=0.3, random_state=0)

In [23]:
from sklearn import ensemble
clf=ensemble.GradientBoostingClassifier(n_estimators=50)
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.83208955223880599

In [32]:
test=pd.read_csv('test.csv', header=0)

In [33]:
#Remove Unnecessary Columns
test=test.drop(unnecessary_columns, axis=1)

In [34]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 0 to 417
Data columns (total 8 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Fare           417 non-null float64
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(2)
memory usage: 29.4+ KB

In [35]:
#Convert to Categorical
dummies=[]
cols=['Pclass', 'Sex', 'Embarked']
for col in cols:
    dummies.append(pd.get_dummies(test[col]))
test_dummies=pd.concat(dummies, axis=1)
test=pd.concat((test, test_dummies), axis=1)

#Remove after Converstion
test=test.drop(cols, axis=1)

In [36]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 0 to 417
Data columns (total 13 columns):
PassengerId    418 non-null int64
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Fare           417 non-null float64
1              418 non-null float64
2              418 non-null float64
3              418 non-null float64
female         418 non-null float64
male           418 non-null float64
C              418 non-null float64
Q              418 non-null float64
S              418 non-null float64
dtypes: float64(10), int64(3)
memory usage: 45.7 KB

In [40]:
#Deal with missing value
test['Fare']=test['Fare'].interpolate()
test['Age']=test['Age'].interpolate()

In [41]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 0 to 417
Data columns (total 13 columns):
PassengerId    418 non-null int64
Age            418 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Fare           418 non-null float64
1              418 non-null float64
2              418 non-null float64
3              418 non-null float64
female         418 non-null float64
male           418 non-null float64
C              418 non-null float64
Q              418 non-null float64
S              418 non-null float64
dtypes: float64(10), int64(3)
memory usage: 45.7 KB

In [46]:
X_results=test.values

In [47]:
y_results=clf.predict(X_results)

In [48]:
output=np.column_stack((X_results[:, 0], y_results))

In [49]:
output.info()

AttributeError: 'numpy.ndarray' object has no attribute 'info'

In [50]:
output

array([[  8.92000000e+02,   0.00000000e+00],
       [  8.93000000e+02,   0.00000000e+00],
       [  8.94000000e+02,   0.00000000e+00],
       [  8.95000000e+02,   0.00000000e+00],
       [  8.96000000e+02,   0.00000000e+00],
       [  8.97000000e+02,   1.00000000e+00],
       [  8.98000000e+02,   1.00000000e+00],
       [  8.99000000e+02,   0.00000000e+00],
       [  9.00000000e+02,   1.00000000e+00],
       [  9.01000000e+02,   0.00000000e+00],
       [  9.02000000e+02,   0.00000000e+00],
       [  9.03000000e+02,   0.00000000e+00],
       [  9.04000000e+02,   1.00000000e+00],
       [  9.05000000e+02,   0.00000000e+00],
       [  9.06000000e+02,   1.00000000e+00],
       [  9.07000000e+02,   1.00000000e+00],
       [  9.08000000e+02,   0.00000000e+00],
       [  9.09000000e+02,   0.00000000e+00],
       [  9.10000000e+02,   0.00000000e+00],
       [  9.11000000e+02,   0.00000000e+00],
       [  9.12000000e+02,   0.00000000e+00],
       [  9.13000000e+02,   0.00000000e+00],
       [  9.14000000e+02,   1.00000000e+00],
       [  9.15000000e+02,   1.00000000e+00],
       [  9.16000000e+02,   1.00000000e+00],
       [  9.17000000e+02,   0.00000000e+00],
       [  9.18000000e+02,   1.00000000e+00],
       [  9.19000000e+02,   0.00000000e+00],
       [  9.20000000e+02,   1.00000000e+00],
       [  9.21000000e+02,   0.00000000e+00],
       [  9.22000000e+02,   0.00000000e+00],
       [  9.23000000e+02,   0.00000000e+00],
       [  9.24000000e+02,   0.00000000e+00],
       [  9.25000000e+02,   0.00000000e+00],
       [  9.26000000e+02,   1.00000000e+00],
       [  9.27000000e+02,   0.00000000e+00],
       [  9.28000000e+02,   0.00000000e+00],
       [  9.29000000e+02,   0.00000000e+00],
       [  9.30000000e+02,   0.00000000e+00],
       [  9.31000000e+02,   1.00000000e+00],
       [  9.32000000e+02,   0.00000000e+00],
       [  9.33000000e+02,   1.00000000e+00],
       [  9.34000000e+02,   0.00000000e+00],
       [  9.35000000e+02,   1.00000000e+00],
       [  9.36000000e+02,   1.00000000e+00],
       [  9.37000000e+02,   0.00000000e+00],
       [  9.38000000e+02,   1.00000000e+00],
       [  9.39000000e+02,   0.00000000e+00],
       [  9.40000000e+02,   1.00000000e+00],
       [  9.41000000e+02,   0.00000000e+00],
       [  9.42000000e+02,   1.00000000e+00],
       [  9.43000000e+02,   0.00000000e+00],
       [  9.44000000e+02,   1.00000000e+00],
       [  9.45000000e+02,   1.00000000e+00],
       [  9.46000000e+02,   0.00000000e+00],
       [  9.47000000e+02,   0.00000000e+00],
       [  9.48000000e+02,   0.00000000e+00],
       [  9.49000000e+02,   0.00000000e+00],
       [  9.50000000e+02,   0.00000000e+00],
       [  9.51000000e+02,   1.00000000e+00],
       [  9.52000000e+02,   0.00000000e+00],
       [  9.53000000e+02,   1.00000000e+00],
       [  9.54000000e+02,   0.00000000e+00],
       [  9.55000000e+02,   1.00000000e+00],
       [  9.56000000e+02,   1.00000000e+00],
       [  9.57000000e+02,   1.00000000e+00],
       [  9.58000000e+02,   1.00000000e+00],
       [  9.59000000e+02,   1.00000000e+00],
       [  9.60000000e+02,   1.00000000e+00],
       [  9.61000000e+02,   1.00000000e+00],
       [  9.62000000e+02,   1.00000000e+00],
       [  9.63000000e+02,   0.00000000e+00],
       [  9.64000000e+02,   0.00000000e+00],
       [  9.65000000e+02,   1.00000000e+00],
       [  9.66000000e+02,   1.00000000e+00],
       [  9.67000000e+02,   1.00000000e+00],
       [  9.68000000e+02,   0.00000000e+00],
       [  9.69000000e+02,   1.00000000e+00],
       [  9.70000000e+02,   0.00000000e+00],
       [  9.71000000e+02,   1.00000000e+00],
       [  9.72000000e+02,   1.00000000e+00],
       [  9.73000000e+02,   0.00000000e+00],
       [  9.74000000e+02,   0.00000000e+00],
       [  9.75000000e+02,   0.00000000e+00],
       [  9.76000000e+02,   0.00000000e+00],
       [  9.77000000e+02,   0.00000000e+00],
       [  9.78000000e+02,   1.00000000e+00],
       [  9.79000000e+02,   0.00000000e+00],
       [  9.80000000e+02,   1.00000000e+00],
       [  9.81000000e+02,   1.00000000e+00],
       [  9.82000000e+02,   0.00000000e+00],
       [  9.83000000e+02,   0.00000000e+00],
       [  9.84000000e+02,   1.00000000e+00],
       [  9.85000000e+02,   0.00000000e+00],
       [  9.86000000e+02,   1.00000000e+00],
       [  9.87000000e+02,   0.00000000e+00],
       [  9.88000000e+02,   1.00000000e+00],
       [  9.89000000e+02,   0.00000000e+00],
       [  9.90000000e+02,   0.00000000e+00],
       [  9.91000000e+02,   0.00000000e+00],
       [  9.92000000e+02,   1.00000000e+00],
       [  9.93000000e+02,   0.00000000e+00],
       [  9.94000000e+02,   0.00000000e+00],
       [  9.95000000e+02,   0.00000000e+00],
       [  9.96000000e+02,   1.00000000e+00],
       [  9.97000000e+02,   0.00000000e+00],
       [  9.98000000e+02,   0.00000000e+00],
       [  9.99000000e+02,   0.00000000e+00],
       [  1.00000000e+03,   0.00000000e+00],
       [  1.00100000e+03,   0.00000000e+00],
       [  1.00200000e+03,   0.00000000e+00],
       [  1.00300000e+03,   0.00000000e+00],
       [  1.00400000e+03,   1.00000000e+00],
       [  1.00500000e+03,   1.00000000e+00],
       [  1.00600000e+03,   1.00000000e+00],
       [  1.00700000e+03,   0.00000000e+00],
       [  1.00800000e+03,   0.00000000e+00],
       [  1.00900000e+03,   1.00000000e+00],
       [  1.01000000e+03,   1.00000000e+00],
       [  1.01100000e+03,   1.00000000e+00],
       [  1.01200000e+03,   1.00000000e+00],
       [  1.01300000e+03,   0.00000000e+00],
       [  1.01400000e+03,   1.00000000e+00],
       [  1.01500000e+03,   0.00000000e+00],
       [  1.01600000e+03,   0.00000000e+00],
       [  1.01700000e+03,   0.00000000e+00],
       [  1.01800000e+03,   0.00000000e+00],
       [  1.01900000e+03,   1.00000000e+00],
       [  1.02000000e+03,   0.00000000e+00],
       [  1.02100000e+03,   0.00000000e+00],
       [  1.02200000e+03,   1.00000000e+00],
       [  1.02300000e+03,   0.00000000e+00],
       [  1.02400000e+03,   0.00000000e+00],
       [  1.02500000e+03,   0.00000000e+00],
       [  1.02600000e+03,   0.00000000e+00],
       [  1.02700000e+03,   0.00000000e+00],
       [  1.02800000e+03,   0.00000000e+00],
       [  1.02900000e+03,   0.00000000e+00],
       [  1.03000000e+03,   0.00000000e+00],
       [  1.03100000e+03,   0.00000000e+00],
       [  1.03200000e+03,   0.00000000e+00],
       [  1.03300000e+03,   1.00000000e+00],
       [  1.03400000e+03,   0.00000000e+00],
       [  1.03500000e+03,   0.00000000e+00],
       [  1.03600000e+03,   1.00000000e+00],
       [  1.03700000e+03,   0.00000000e+00],
       [  1.03800000e+03,   1.00000000e+00],
       [  1.03900000e+03,   0.00000000e+00],
       [  1.04000000e+03,   1.00000000e+00],
       [  1.04100000e+03,   0.00000000e+00],
       [  1.04200000e+03,   1.00000000e+00],
       [  1.04300000e+03,   0.00000000e+00],
       [  1.04400000e+03,   0.00000000e+00],
       [  1.04500000e+03,   0.00000000e+00],
       [  1.04600000e+03,   0.00000000e+00],
       [  1.04700000e+03,   0.00000000e+00],
       [  1.04800000e+03,   1.00000000e+00],
       [  1.04900000e+03,   0.00000000e+00],
       [  1.05000000e+03,   1.00000000e+00],
       [  1.05100000e+03,   0.00000000e+00],
       [  1.05200000e+03,   1.00000000e+00],
       [  1.05300000e+03,   1.00000000e+00],
       [  1.05400000e+03,   1.00000000e+00],
       [  1.05500000e+03,   0.00000000e+00],
       [  1.05600000e+03,   0.00000000e+00],
       [  1.05700000e+03,   0.00000000e+00],
       [  1.05800000e+03,   1.00000000e+00],
       [  1.05900000e+03,   0.00000000e+00],
       [  1.06000000e+03,   1.00000000e+00],
       [  1.06100000e+03,   0.00000000e+00],
       [  1.06200000e+03,   0.00000000e+00],
       [  1.06300000e+03,   0.00000000e+00],
       [  1.06400000e+03,   0.00000000e+00],
       [  1.06500000e+03,   0.00000000e+00],
       [  1.06600000e+03,   0.00000000e+00],
       [  1.06700000e+03,   1.00000000e+00],
       [  1.06800000e+03,   1.00000000e+00],
       [  1.06900000e+03,   0.00000000e+00],
       [  1.07000000e+03,   1.00000000e+00],
       [  1.07100000e+03,   1.00000000e+00],
       [  1.07200000e+03,   0.00000000e+00],
       [  1.07300000e+03,   1.00000000e+00],
       [  1.07400000e+03,   1.00000000e+00],
       [  1.07500000e+03,   0.00000000e+00],
       [  1.07600000e+03,   1.00000000e+00],
       [  1.07700000e+03,   0.00000000e+00],
       [  1.07800000e+03,   1.00000000e+00],
       [  1.07900000e+03,   0.00000000e+00],
       [  1.08000000e+03,   0.00000000e+00],
       [  1.08100000e+03,   0.00000000e+00],
       [  1.08200000e+03,   0.00000000e+00],
       [  1.08300000e+03,   0.00000000e+00],
       [  1.08400000e+03,   1.00000000e+00],
       [  1.08500000e+03,   0.00000000e+00],
       [  1.08600000e+03,   1.00000000e+00],
       [  1.08700000e+03,   0.00000000e+00],
       [  1.08800000e+03,   1.00000000e+00],
       [  1.08900000e+03,   0.00000000e+00],
       [  1.09000000e+03,   0.00000000e+00],
       [  1.09100000e+03,   0.00000000e+00],
       [  1.09200000e+03,   1.00000000e+00],
       [  1.09300000e+03,   1.00000000e+00],
       [  1.09400000e+03,   1.00000000e+00],
       [  1.09500000e+03,   1.00000000e+00],
       [  1.09600000e+03,   0.00000000e+00],
       [  1.09700000e+03,   1.00000000e+00],
       [  1.09800000e+03,   1.00000000e+00],
       [  1.09900000e+03,   0.00000000e+00],
       [  1.10000000e+03,   1.00000000e+00],
       [  1.10100000e+03,   0.00000000e+00],
       [  1.10200000e+03,   1.00000000e+00],
       [  1.10300000e+03,   0.00000000e+00],
       [  1.10400000e+03,   0.00000000e+00],
       [  1.10500000e+03,   1.00000000e+00],
       [  1.10600000e+03,   0.00000000e+00],
       [  1.10700000e+03,   1.00000000e+00],
       [  1.10800000e+03,   0.00000000e+00],
       [  1.10900000e+03,   0.00000000e+00],
       [  1.11000000e+03,   1.00000000e+00],
       [  1.11100000e+03,   0.00000000e+00],
       [  1.11200000e+03,   1.00000000e+00],
       [  1.11300000e+03,   0.00000000e+00],
       [  1.11400000e+03,   1.00000000e+00],
       [  1.11500000e+03,   0.00000000e+00],
       [  1.11600000e+03,   1.00000000e+00],
       [  1.11700000e+03,   0.00000000e+00],
       [  1.11800000e+03,   0.00000000e+00],
       [  1.11900000e+03,   1.00000000e+00],
       [  1.12000000e+03,   0.00000000e+00],
       [  1.12100000e+03,   0.00000000e+00],
       [  1.12200000e+03,   1.00000000e+00],
       [  1.12300000e+03,   1.00000000e+00],
       [  1.12400000e+03,   0.00000000e+00],
       [  1.12500000e+03,   0.00000000e+00],
       [  1.12600000e+03,   1.00000000e+00],
       [  1.12700000e+03,   0.00000000e+00],
       [  1.12800000e+03,   0.00000000e+00],
       [  1.12900000e+03,   0.00000000e+00],
       [  1.13000000e+03,   1.00000000e+00],
       [  1.13100000e+03,   1.00000000e+00],
       [  1.13200000e+03,   1.00000000e+00],
       [  1.13300000e+03,   1.00000000e+00],
       [  1.13400000e+03,   1.00000000e+00],
       [  1.13500000e+03,   0.00000000e+00],
       [  1.13600000e+03,   0.00000000e+00],
       [  1.13700000e+03,   1.00000000e+00],
       [  1.13800000e+03,   1.00000000e+00],
       [  1.13900000e+03,   0.00000000e+00],
       [  1.14000000e+03,   1.00000000e+00],
       [  1.14100000e+03,   1.00000000e+00],
       [  1.14200000e+03,   0.00000000e+00],
       [  1.14300000e+03,   0.00000000e+00],
       [  1.14400000e+03,   1.00000000e+00],
       [  1.14500000e+03,   0.00000000e+00],
       [  1.14600000e+03,   0.00000000e+00],
       [  1.14700000e+03,   0.00000000e+00],
       [  1.14800000e+03,   0.00000000e+00],
       [  1.14900000e+03,   0.00000000e+00],
       [  1.15000000e+03,   1.00000000e+00],
       [  1.15100000e+03,   0.00000000e+00],
       [  1.15200000e+03,   0.00000000e+00],
       [  1.15300000e+03,   0.00000000e+00],
       [  1.15400000e+03,   1.00000000e+00],
       [  1.15500000e+03,   1.00000000e+00],
       [  1.15600000e+03,   0.00000000e+00],
       [  1.15700000e+03,   0.00000000e+00],
       [  1.15800000e+03,   0.00000000e+00],
       [  1.15900000e+03,   0.00000000e+00],
       [  1.16000000e+03,   0.00000000e+00],
       [  1.16100000e+03,   0.00000000e+00],
       [  1.16200000e+03,   1.00000000e+00],
       [  1.16300000e+03,   0.00000000e+00],
       [  1.16400000e+03,   1.00000000e+00],
       [  1.16500000e+03,   1.00000000e+00],
       [  1.16600000e+03,   0.00000000e+00],
       [  1.16700000e+03,   1.00000000e+00],
       [  1.16800000e+03,   0.00000000e+00],
       [  1.16900000e+03,   0.00000000e+00],
       [  1.17000000e+03,   0.00000000e+00],
       [  1.17100000e+03,   0.00000000e+00],
       [  1.17200000e+03,   0.00000000e+00],
       [  1.17300000e+03,   1.00000000e+00],
       [  1.17400000e+03,   0.00000000e+00],
       [  1.17500000e+03,   1.00000000e+00],
       [  1.17600000e+03,   1.00000000e+00],
       [  1.17700000e+03,   0.00000000e+00],
       [  1.17800000e+03,   0.00000000e+00],
       [  1.17900000e+03,   1.00000000e+00],
       [  1.18000000e+03,   0.00000000e+00],
       [  1.18100000e+03,   0.00000000e+00],
       [  1.18200000e+03,   1.00000000e+00],
       [  1.18300000e+03,   0.00000000e+00],
       [  1.18400000e+03,   0.00000000e+00],
       [  1.18500000e+03,   0.00000000e+00],
       [  1.18600000e+03,   0.00000000e+00],
       [  1.18700000e+03,   0.00000000e+00],
       [  1.18800000e+03,   0.00000000e+00],
       [  1.18900000e+03,   0.00000000e+00],
       [  1.19000000e+03,   1.00000000e+00],
       [  1.19100000e+03,   0.00000000e+00],
       [  1.19200000e+03,   0.00000000e+00],
       [  1.19300000e+03,   0.00000000e+00],
       [  1.19400000e+03,   0.00000000e+00],
       [  1.19500000e+03,   0.00000000e+00],
       [  1.19600000e+03,   0.00000000e+00],
       [  1.19700000e+03,   1.00000000e+00],
       [  1.19800000e+03,   1.00000000e+00],
       [  1.19900000e+03,   1.00000000e+00],
       [  1.20000000e+03,   0.00000000e+00],
       [  1.20100000e+03,   0.00000000e+00],
       [  1.20200000e+03,   0.00000000e+00],
       [  1.20300000e+03,   0.00000000e+00],
       [  1.20400000e+03,   0.00000000e+00],
       [  1.20500000e+03,   0.00000000e+00],
       [  1.20600000e+03,   1.00000000e+00],
       [  1.20700000e+03,   1.00000000e+00],
       [  1.20800000e+03,   1.00000000e+00],
       [  1.20900000e+03,   0.00000000e+00],
       [  1.21000000e+03,   0.00000000e+00],
       [  1.21100000e+03,   0.00000000e+00],
       [  1.21200000e+03,   0.00000000e+00],
       [  1.21300000e+03,   0.00000000e+00],
       [  1.21400000e+03,   0.00000000e+00],
       [  1.21500000e+03,   1.00000000e+00],
       [  1.21600000e+03,   1.00000000e+00],
       [  1.21700000e+03,   0.00000000e+00],
       [  1.21800000e+03,   1.00000000e+00],
       [  1.21900000e+03,   1.00000000e+00],
       [  1.22000000e+03,   0.00000000e+00],
       [  1.22100000e+03,   0.00000000e+00],
       [  1.22200000e+03,   1.00000000e+00],
       [  1.22300000e+03,   1.00000000e+00],
       [  1.22400000e+03,   0.00000000e+00],
       [  1.22500000e+03,   1.00000000e+00],
       [  1.22600000e+03,   0.00000000e+00],
       [  1.22700000e+03,   1.00000000e+00],
       [  1.22800000e+03,   1.00000000e+00],
       [  1.22900000e+03,   0.00000000e+00],
       [  1.23000000e+03,   0.00000000e+00],
       [  1.23100000e+03,   0.00000000e+00],
       [  1.23200000e+03,   0.00000000e+00],
       [  1.23300000e+03,   0.00000000e+00],
       [  1.23400000e+03,   0.00000000e+00],
       [  1.23500000e+03,   1.00000000e+00],
       [  1.23600000e+03,   0.00000000e+00],
       [  1.23700000e+03,   0.00000000e+00],
       [  1.23800000e+03,   0.00000000e+00],
       [  1.23900000e+03,   0.00000000e+00],
       [  1.24000000e+03,   0.00000000e+00],
       [  1.24100000e+03,   1.00000000e+00],
       [  1.24200000e+03,   1.00000000e+00],
       [  1.24300000e+03,   0.00000000e+00],
       [  1.24400000e+03,   0.00000000e+00],
       [  1.24500000e+03,   0.00000000e+00],
       [  1.24600000e+03,   1.00000000e+00],
       [  1.24700000e+03,   0.00000000e+00],
       [  1.24800000e+03,   1.00000000e+00],
       [  1.24900000e+03,   0.00000000e+00],
       [  1.25000000e+03,   0.00000000e+00],
       [  1.25100000e+03,   0.00000000e+00],
       [  1.25200000e+03,   0.00000000e+00],
       [  1.25300000e+03,   1.00000000e+00],
       [  1.25400000e+03,   1.00000000e+00],
       [  1.25500000e+03,   0.00000000e+00],
       [  1.25600000e+03,   1.00000000e+00],
       [  1.25700000e+03,   0.00000000e+00],
       [  1.25800000e+03,   0.00000000e+00],
       [  1.25900000e+03,   0.00000000e+00],
       [  1.26000000e+03,   1.00000000e+00],
       [  1.26100000e+03,   0.00000000e+00],
       [  1.26200000e+03,   0.00000000e+00],
       [  1.26300000e+03,   1.00000000e+00],
       [  1.26400000e+03,   0.00000000e+00],
       [  1.26500000e+03,   0.00000000e+00],
       [  1.26600000e+03,   1.00000000e+00],
       [  1.26700000e+03,   1.00000000e+00],
       [  1.26800000e+03,   0.00000000e+00],
       [  1.26900000e+03,   0.00000000e+00],
       [  1.27000000e+03,   0.00000000e+00],
       [  1.27100000e+03,   0.00000000e+00],
       [  1.27200000e+03,   0.00000000e+00],
       [  1.27300000e+03,   0.00000000e+00],
       [  1.27400000e+03,   0.00000000e+00],
       [  1.27500000e+03,   0.00000000e+00],
       [  1.27600000e+03,   0.00000000e+00],
       [  1.27700000e+03,   1.00000000e+00],
       [  1.27800000e+03,   0.00000000e+00],
       [  1.27900000e+03,   0.00000000e+00],
       [  1.28000000e+03,   0.00000000e+00],
       [  1.28100000e+03,   0.00000000e+00],
       [  1.28200000e+03,   1.00000000e+00],
       [  1.28300000e+03,   1.00000000e+00],
       [  1.28400000e+03,   1.00000000e+00],
       [  1.28500000e+03,   0.00000000e+00],
       [  1.28600000e+03,   0.00000000e+00],
       [  1.28700000e+03,   1.00000000e+00],
       [  1.28800000e+03,   0.00000000e+00],
       [  1.28900000e+03,   1.00000000e+00],
       [  1.29000000e+03,   0.00000000e+00],
       [  1.29100000e+03,   0.00000000e+00],
       [  1.29200000e+03,   1.00000000e+00],
       [  1.29300000e+03,   0.00000000e+00],
       [  1.29400000e+03,   1.00000000e+00],
       [  1.29500000e+03,   1.00000000e+00],
       [  1.29600000e+03,   1.00000000e+00],
       [  1.29700000e+03,   0.00000000e+00],
       [  1.29800000e+03,   0.00000000e+00],
       [  1.29900000e+03,   1.00000000e+00],
       [  1.30000000e+03,   1.00000000e+00],
       [  1.30100000e+03,   1.00000000e+00],
       [  1.30200000e+03,   1.00000000e+00],
       [  1.30300000e+03,   1.00000000e+00],
       [  1.30400000e+03,   0.00000000e+00],
       [  1.30500000e+03,   0.00000000e+00],
       [  1.30600000e+03,   1.00000000e+00],
       [  1.30700000e+03,   0.00000000e+00],
       [  1.30800000e+03,   0.00000000e+00],
       [  1.30900000e+03,   0.00000000e+00]])

In [51]:
output.shape

(418L, 2L)

In [52]:
df_results=pd.DataFrame(output.astype('int'), columns=['PassengerID', 'Survived'])

In [53]:
df_results.to_csv('titanic_results.csv', index=False)

In [45]:
test

     PassengerId   Age  SibSp  Parch      Fare  1  2  3  female  male  C  Q  S
0            892  34.5      0      0    7.8292  0  0  1       0     1  0  1  0
1            893  47.0      1      0    7.0000  0  0  1       1     0  0  0  1
2            894  62.0      0      0    9.6875  0  1  0       0     1  0  1  0
3            895  27.0      0      0    8.6625  0  0  1       0     1  0  0  1
4            896  22.0      1      1   12.2875  0  0  1       1     0  0  0  1
5            897  14.0      0      0    9.2250  0  0  1       0     1  0  0  1
6            898  30.0      0      0    7.6292  0  0  1       1     0  0  1  0
7            899  26.0      1      1   29.0000  0  1  0       0     1  0  0  1
8            900  18.0      0      0    7.2292  0  0  1       1     0  1  0  0
9            901  21.0      2      0   24.1500  0  0  1       0     1  0  0  1
10           902  33.5      0      0    7.8958  0  0  1       0     1  0  0  1
11           903  46.0      0      0   26.0000  1  0  0       0     1  0  0  1
12           904  23.0      1      0   82.2667  1  0  0       1     0  0  0  1
13           905  63.0      1      0   26.0000  0  1  0       0     1  0  0  1
14           906  47.0      1      0   61.1750  1  0  0       1     0  0  0  1
15           907  24.0      1      0   27.7208  0  1  0       1     0  1  0  0
16           908  35.0      0      0   12.3500  0  1  0       0     1  0  1  0
17           909  21.0      0      0    7.2250  0  0  1       0     1  1  0  0
18           910  27.0      1      0    7.9250  0  0  1       1     0  0  0  1
19           911  45.0      0      0    7.2250  0  0  1       1     0  1  0  0
20           912  55.0      1      0   59.4000  1  0  0       0     1  1  0  0
21           913   9.0      0      1    3.1708  0  0  1       0     1  0  0  1
22           914  15.0      0      0   31.6833  1  0  0       1     0  0  0  1
23           915  21.0      0      1   61.3792  1  0  0       0     1  1  0  0
24           916  48.0      1      3  262.3750  1  0  0       1     0  1  0  0
25           917  50.0      1      0   14.5000  0  0  1       0     1  0  0  1
26           918  22.0      0      1   61.9792  1  0  0       1     0  1  0  0
27           919  22.5      0      0    7.2250  0  0  1       0     1  1  0  0
28           920  41.0      0      0   30.5000  1  0  0       0     1  0  0  1
29           921  45.5      2      0   21.6792  0  0  1       0     1  1  0  0
..           ...   ...    ...    ...       ... .. .. ..     ...   ... .. .. ..
388         1280  21.0      0      0    7.7500  0  0  1       0     1  0  1  0
389         1281   6.0      3      1   21.0750  0  0  1       0     1  0  0  1
390         1282  23.0      0      0   93.5000  1  0  0       0     1  0  0  1
391         1283  51.0      0      1   39.4000  1  0  0       1     0  0  0  1
392         1284  13.0      0      2   20.2500  0  0  1       0     1  0  0  1
393         1285  47.0      0      0   10.5000  0  1  0       0     1  0  0  1
394         1286  29.0      3      1   22.0250  0  0  1       0     1  0  0  1
395         1287  18.0      1      0   60.0000  1  0  0       1     0  0  0  1
396         1288  24.0      0      0    7.2500  0  0  1       0     1  0  1  0
397         1289  48.0      1      1   79.2000  1  0  0       1     0  1  0  0
398         1290  22.0      0      0    7.7750  0  0  1       0     1  0  0  1
399         1291  31.0      0      0    7.7333  0  0  1       0     1  0  1  0
400         1292  30.0      0      0  164.8667  1  0  0       1     0  0  0  1
401         1293  38.0      1      0   21.0000  0  1  0       0     1  0  0  1
402         1294  22.0      0      1   59.4000  1  0  0       1     0  1  0  0
403         1295  17.0      0      0   47.1000  1  0  0       0     1  0  0  1
404         1296  43.0      1      0   27.7208  1  0  0       0     1  1  0  0
405         1297  20.0      0      0   13.8625  0  1  0       0     1  1  0  0
406         1298  23.0      1      0   10.5000  0  1  0       0     1  0  0  1
407         1299  50.0      1      1  211.5000  1  0  0       0     1  1  0  0
408         1300  26.5      0      0    7.7208  0  0  1       1     0  0  1  0
409         1301   3.0      1      1   13.7750  0  0  1       1     0  0  0  1
410         1302  20.0      0      0    7.7500  0  0  1       1     0  0  1  0
411         1303  37.0      1      0   90.0000  1  0  0       1     0  0  1  0
412         1304  28.0      0      0    7.7750  0  0  1       1     0  0  0  1
413         1305  33.5      0      0    8.0500  0  0  1       0     1  0  0  1
414         1306  39.0      0      0  108.9000  1  0  0       1     0  1  0  0
415         1307  38.5      0      0    7.2500  0  0  1       0     1  0  0  1
416         1308  38.5      0      0    8.0500  0  0  1       0     1  0  0  1
417         1309  38.5      1      1   22.3583  0  0  1       0     1  1  0  0

[418 rows x 13 columns]

In [ ]:
df.info()